[package]
name = "block_rain"
version = "0.1.0"
edition = "2021"
authors = ["ink-carp <18020970773@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcg_with_xorshift = "1.0.0"
raw_terminal = "0.1.0"